apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  ports:
  - port: http
    targetPort: http
  selector:
    app: guestbook
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: guestbook-https
  namespace: examples
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`guestbook.kefych.net`)
    priority: 10
    services:
    - kind: Service
      name: guestbook
      port: http
  tls:
    secretName: tls-argocd
